---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: waybluefin
# description will be included in the image's metadata
description: Wayblue with a bluefin touch

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - libspng
  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-42/solopasha-hyprland-fedora-42.repo
      copr:
        - solopasha/hyprland
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:solopasha:hyprland
        allow-erasing: true
        packages:
          - hyprland
    install:
      packages:
        - repo: copr:copr.fedorainfracloud.org:solopasha:hyprland
          packages:
          - hyprutils
          - hyprsunset
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-42/solopasha-hyprland-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/packages/repo/fedora-%OS_VERSION%/errornointernet-packages-fedora-%OS_VERSION%.repo
    install:
      - hypridle
      - hyprlock
      - micro
      - curl
      - gawk
      - git
      - grim
      - hyprpolkitagent
      - ImageMagick
      - inxi
      - jq
      - kitty
      - kvantum
      - nano
      - network-manager-applet
      - openssl
      - pamixer
      - pavucontrol
      - pipewire-alsa
      - pipewire-utils
      - playerctl
      - python3-requests
      - python3-pip
      - python3-pyquery
      - qt5ct
      - qt6ct
      - qt6-qtsvg
      - rofi-wayland
      - slurp
      - swappy
      - wget2
      - wl-clipboard
      - wlogout
      - xdg-user-dirs
      - xdg-utils
      - yad
      - cliphist
      - nwg-look
      - SwayNotificationCenter
      - pamixer
      - swww
      - wallust 
      - waydroid
      - unzip
      - tar
      - gnome-keyring
      - libsecret
    remove:
      - firefox
      - firefox-langpacks 
  - type: default-flatpaks
    system:  
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - net.nokyan.Resources # this Flatpak is appended to the install list
        - app.zen_browser.zen # this one too
        - io.anytype.anytype # this one too
        - com.spotify.Client # gotta somehow figure out spicetify
        - io.github.celluloid_player.Celluloid # look videos!!
        - com.unicornsonlsd.finamp
        - io.github.shiftey.Desktop
        - com.vscodium.codium
  - type: systemd
    system:  
      enabled:
        - spotpermfix.service
        - podman.socket
        - hyprsunset.service
  - type: justfiles
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  - type: script
    snippets:
      - "chmod +x ublue-bling"
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

